# 模拟达人数据 - 三个平台各10名海外达人

TIKTOK_INFLUENCERS = [
    {
        "id": "tt001",
        "platform": "tiktok",
        "nickname": "@beautytips_jess",
        "real_name": "Jessica Moore",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=jess",
        "followers": "128k",
        "followers_num": 128000,
        "avg_likes": "4.5k",
        "avg_comments": 230,
        "avg_views": "85k",
        "engagement_rate": "3.5%",
        "price_usd": 500,
        "price_display": "$500",
        "tags": ["美妆测评", "平价好物", "护肤"],
        "region": "美国-洛杉矶",
        "country": "US",
        "bio": "Affordable beauty tips for everyday gals 💄 | skincare obsessed",
        "past_brands": ["Shein", "e.l.f. Cosmetics", "NYX"],
        "fake_risk": 12,
        "niche": "beauty",
        "language": "English",
        "email": "jess.beauty@gmail.com"
    },
    {
        "id": "tt002",
        "platform": "tiktok",
        "nickname": "@fitlife_marcus",
        "real_name": "Marcus Johnson",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=marcus",
        "followers": "342k",
        "followers_num": 342000,
        "avg_likes": "12.3k",
        "avg_comments": 580,
        "avg_views": "220k",
        "engagement_rate": "3.6%",
        "price_usd": 1200,
        "price_display": "$1,200",
        "tags": ["健身", "运动装备", "营养补充"],
        "region": "英国-伦敦",
        "country": "UK",
        "bio": "Fitness journey 💪 | Helping you reach your goals | PT certified",
        "past_brands": ["Gymshark", "MyProtein", "Nike"],
        "fake_risk": 8,
        "niche": "fitness",
        "language": "English",
        "email": "marcus.fit@outlook.com"
    },
    {
        "id": "tt003",
        "platform": "tiktok",
        "nickname": "@techunbox_ryan",
        "real_name": "Ryan Chen",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=ryan",
        "followers": "89k",
        "followers_num": 89000,
        "avg_likes": "3.2k",
        "avg_comments": 145,
        "avg_views": "62k",
        "engagement_rate": "3.6%",
        "price_usd": 380,
        "price_display": "$380",
        "tags": ["数码开箱", "科技评测", "好物推荐"],
        "region": "美国-西雅图",
        "country": "US",
        "bio": "Tech nerd who loves gadgets 📱 | Unboxing & honest reviews",
        "past_brands": ["Anker", "Baseus", "Aukey"],
        "fake_risk": 15,
        "niche": "tech",
        "language": "English",
        "email": "ryan.tech@gmail.com"
    },
    {
        "id": "tt004",
        "platform": "tiktok",
        "nickname": "@homecook_sofia",
        "real_name": "Sofia Martinez",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=sofia",
        "followers": "256k",
        "followers_num": 256000,
        "avg_likes": "9.8k",
        "avg_comments": 420,
        "avg_views": "180k",
        "engagement_rate": "3.8%",
        "price_usd": 900,
        "price_display": "$900",
        "tags": ["美食料理", "家常菜", "厨房好物"],
        "region": "美国-迈阿密",
        "country": "US",
        "bio": "Home chef 🍳 | Easy recipes for busy families | Latina cooking",
        "past_brands": ["Amazon Basics", "Tefal", "OXO"],
        "fake_risk": 7,
        "niche": "food",
        "language": "English/Spanish",
        "email": "sofia.cooks@gmail.com"
    },
    {
        "id": "tt005",
        "platform": "tiktok",
        "nickname": "@fashionista_nadia",
        "real_name": "Nadia Williams",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=nadia",
        "followers": "512k",
        "followers_num": 512000,
        "avg_likes": "18.6k",
        "avg_comments": 890,
        "avg_views": "350k",
        "engagement_rate": "3.6%",
        "price_usd": 2500,
        "price_display": "$2,500",
        "tags": ["时尚穿搭", "OOTD", "平价潮流"],
        "region": "英国-曼彻斯特",
        "country": "UK",
        "bio": "Style on a budget ✨ | Daily OOTD | UK fashion lover",
        "past_brands": ["ASOS", "Shein", "Pretty Little Thing"],
        "fake_risk": 18,
        "niche": "fashion",
        "language": "English",
        "email": "nadia.fashion@hotmail.com"
    },
    {
        "id": "tt006",
        "platform": "tiktok",
        "nickname": "@petlover_anya",
        "real_name": "Anya Patel",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=anya",
        "followers": "175k",
        "followers_num": 175000,
        "avg_likes": "6.9k",
        "avg_comments": 315,
        "avg_views": "120k",
        "engagement_rate": "3.9%",
        "price_usd": 650,
        "price_display": "$650",
        "tags": ["萌宠", "宠物用品", "猫狗日常"],
        "region": "澳大利亚-悉尼",
        "country": "AU",
        "bio": "Dog mom & cat lover 🐶🐱 | Pet care tips & product reviews",
        "past_brands": ["Chewy", "Petco", "Royal Canin"],
        "fake_risk": 5,
        "niche": "pets",
        "language": "English",
        "email": "anya.pets@gmail.com"
    },
    {
        "id": "tt007",
        "platform": "tiktok",
        "nickname": "@travelwith_jake",
        "real_name": "Jake Thompson",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=jake",
        "followers": "423k",
        "followers_num": 423000,
        "avg_likes": "15.2k",
        "avg_comments": 720,
        "avg_views": "290k",
        "engagement_rate": "3.6%",
        "price_usd": 1800,
        "price_display": "$1,800",
        "tags": ["旅行Vlog", "穷游攻略", "背包客"],
        "region": "加拿大-多伦多",
        "country": "CA",
        "bio": "Budget traveler 🌍 | 50+ countries | Travel hacks & tips",
        "past_brands": ["Booking.com", "Samsonite", "GoPro"],
        "fake_risk": 22,
        "niche": "travel",
        "language": "English",
        "email": "jake.travels@gmail.com"
    },
    {
        "id": "tt008",
        "platform": "tiktok",
        "nickname": "@mua_priya",
        "real_name": "Priya Sharma",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=priya",
        "followers": "198k",
        "followers_num": 198000,
        "avg_likes": "7.8k",
        "avg_comments": 365,
        "avg_views": "145k",
        "engagement_rate": "3.9%",
        "price_usd": 750,
        "price_display": "$750",
        "tags": ["彩妆教程", "深肤色妆容", "南亚美妆"],
        "region": "新加坡",
        "country": "SG",
        "bio": "MUA 💋 | Celebrating brown beauty | Makeup tutorials for all",
        "past_brands": ["Fenty Beauty", "NYX", "ColourPop"],
        "fake_risk": 9,
        "niche": "beauty",
        "language": "English",
        "email": "priya.mua@gmail.com"
    },
    {
        "id": "tt009",
        "platform": "tiktok",
        "nickname": "@gadgetguru_thai",
        "real_name": "Thanakrit Lim",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=thai",
        "followers": "145k",
        "followers_num": 145000,
        "avg_likes": "5.2k",
        "avg_comments": 248,
        "avg_views": "98k",
        "engagement_rate": "3.6%",
        "price_usd": 480,
        "price_display": "$480",
        "tags": ["数码产品", "平价好物", "东南亚好价"],
        "region": "泰国-曼谷",
        "country": "TH",
        "bio": "Tech deals for Southeast Asia 🔧 | Best gadgets under $50",
        "past_brands": ["Xiaomi", "Realme", "Anker"],
        "fake_risk": 20,
        "niche": "tech",
        "language": "English/Thai",
        "email": "thanakrit.gadget@gmail.com"
    },
    {
        "id": "tt010",
        "platform": "tiktok",
        "nickname": "@momlife_emma",
        "real_name": "Emma Davis",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=emma",
        "followers": "287k",
        "followers_num": 287000,
        "avg_likes": "11.4k",
        "avg_comments": 512,
        "avg_views": "195k",
        "engagement_rate": "4.0%",
        "price_usd": 1050,
        "price_display": "$1,050",
        "tags": ["妈妈博主", "母婴好物", "育儿日常"],
        "region": "美国-芝加哥",
        "country": "US",
        "bio": "Mom of 3 | Sharing motherhood honestly 👶 | Baby & toddler finds",
        "past_brands": ["Carter's", "Skip Hop", "Ergobaby"],
        "fake_risk": 6,
        "niche": "parenting",
        "language": "English",
        "email": "emma.momlife@gmail.com"
    }
]

INSTAGRAM_INFLUENCERS = [
    {
        "id": "ig001",
        "platform": "instagram",
        "nickname": "@glowup_grace",
        "real_name": "Grace Kim",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=grace",
        "followers": "89k",
        "followers_num": 89000,
        "avg_likes": "3.8k",
        "avg_comments": 180,
        "avg_views": "45k",
        "engagement_rate": "4.3%",
        "price_usd": 420,
        "price_display": "$420",
        "tags": ["护肤", "美妆分享", "日系清透"],
        "region": "韩国-首尔",
        "country": "KR",
        "bio": "K-beauty enthusiast ✨ | Skincare routines & honest reviews",
        "past_brands": ["COSRX", "Innisfree", "Sulwhasoo"],
        "fake_risk": 10,
        "niche": "beauty",
        "language": "English/Korean",
        "email": "grace.glow@naver.com"
    },
    {
        "id": "ig002",
        "platform": "instagram",
        "nickname": "@luxeliving_lara",
        "real_name": "Lara Fontaine",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=lara",
        "followers": "215k",
        "followers_num": 215000,
        "avg_likes": "7.6k",
        "avg_comments": 295,
        "avg_views": "120k",
        "engagement_rate": "3.5%",
        "price_usd": 1500,
        "price_display": "$1,500",
        "tags": ["轻奢生活", "家居美学", "简约风格"],
        "region": "法国-巴黎",
        "country": "FR",
        "bio": "Parisian lifestyle 🗼 | Home decor & slow living advocate",
        "past_brands": ["ZARA Home", "H&M HOME", "Amazon"],
        "fake_risk": 14,
        "niche": "lifestyle",
        "language": "English/French",
        "email": "lara.luxe@gmail.com"
    },
    {
        "id": "ig003",
        "platform": "instagram",
        "nickname": "@fitness_freya",
        "real_name": "Freya Hansen",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=freya",
        "followers": "156k",
        "followers_num": 156000,
        "avg_likes": "5.9k",
        "avg_comments": 265,
        "avg_views": "80k",
        "engagement_rate": "3.8%",
        "price_usd": 780,
        "price_display": "$780",
        "tags": ["健身", "北欧风", "运动穿搭"],
        "region": "瑞典-斯德哥尔摩",
        "country": "SE",
        "bio": "Nordic fitness 🏋️ | Sustainable workout gear | Health first",
        "past_brands": ["Gymshark", "Lululemon", "Adidas"],
        "fake_risk": 7,
        "niche": "fitness",
        "language": "English/Swedish",
        "email": "freya.fit@gmail.com"
    },
    {
        "id": "ig004",
        "platform": "instagram",
        "nickname": "@foodie_kenji",
        "real_name": "Kenji Watanabe",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=kenji",
        "followers": "340k",
        "followers_num": 340000,
        "avg_likes": "13.2k",
        "avg_comments": 580,
        "avg_views": "190k",
        "engagement_rate": "3.9%",
        "price_usd": 1800,
        "price_display": "$1,800",
        "tags": ["美食摄影", "日本料理", "街头美食"],
        "region": "日本-东京",
        "country": "JP",
        "bio": "Tokyo food adventures 🍜 | 1000+ restaurants reviewed",
        "past_brands": ["Nikon", "Panasonic", "Kitchen Tools"],
        "fake_risk": 5,
        "niche": "food",
        "language": "English/Japanese",
        "email": "kenji.food@gmail.com"
    },
    {
        "id": "ig005",
        "platform": "instagram",
        "nickname": "@streetstyle_omar",
        "real_name": "Omar Hassan",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=omar",
        "followers": "425k",
        "followers_num": 425000,
        "avg_likes": "16.8k",
        "avg_comments": 720,
        "avg_views": "240k",
        "engagement_rate": "3.9%",
        "price_usd": 2200,
        "price_display": "$2,200",
        "tags": ["街头潮流", "Sneakers", "男装搭配"],
        "region": "美国-纽约",
        "country": "US",
        "bio": "NYC streetwear 🗽 | Sneaker collector | Men's style inspo",
        "past_brands": ["Nike", "Supreme", "Off-White"],
        "fake_risk": 25,
        "niche": "fashion",
        "language": "English",
        "email": "omar.style@gmail.com"
    },
    {
        "id": "ig006",
        "platform": "instagram",
        "nickname": "@wanderlust_mia",
        "real_name": "Mia Rodriguez",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=mia",
        "followers": "198k",
        "followers_num": 198000,
        "avg_likes": "8.1k",
        "avg_comments": 345,
        "avg_views": "110k",
        "engagement_rate": "4.1%",
        "price_usd": 950,
        "price_display": "$950",
        "tags": ["旅行摄影", "小众目的地", "慢旅行"],
        "region": "西班牙-巴塞罗那",
        "country": "ES",
        "bio": "Travel photographer 📸 | Exploring hidden gems worldwide",
        "past_brands": ["AirBnb", "Lonely Planet", "Peak Design"],
        "fake_risk": 11,
        "niche": "travel",
        "language": "English/Spanish",
        "email": "mia.wanders@gmail.com"
    },
    {
        "id": "ig007",
        "platform": "instagram",
        "nickname": "@techreview_ali",
        "real_name": "Ali Abdullah",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=ali",
        "followers": "112k",
        "followers_num": 112000,
        "avg_likes": "4.2k",
        "avg_comments": 198,
        "avg_views": "62k",
        "engagement_rate": "3.7%",
        "price_usd": 550,
        "price_display": "$550",
        "tags": ["科技评测", "手机摄影", "数码好物"],
        "region": "阿联酋-迪拜",
        "country": "AE",
        "bio": "Tech reviews for the Middle East 🔌 | Honest & unbiased",
        "past_brands": ["Samsung", "Huawei", "Anker"],
        "fake_risk": 16,
        "niche": "tech",
        "language": "English/Arabic",
        "email": "ali.tech@gmail.com"
    },
    {
        "id": "ig008",
        "platform": "instagram",
        "nickname": "@plantmom_iris",
        "real_name": "Iris de Vries",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=iris",
        "followers": "78k",
        "followers_num": 78000,
        "avg_likes": "3.4k",
        "avg_comments": 156,
        "avg_views": "42k",
        "engagement_rate": "4.4%",
        "price_usd": 320,
        "price_display": "$320",
        "tags": ["植物养护", "绿植家居", "可持续生活"],
        "region": "荷兰-阿姆斯特丹",
        "country": "NL",
        "bio": "Urban jungle enthusiast 🌿 | 200+ plants | Plant care tips",
        "past_brands": ["IKEA", "Amazon", "Lechuza"],
        "fake_risk": 4,
        "niche": "lifestyle",
        "language": "English/Dutch",
        "email": "iris.plants@gmail.com"
    },
    {
        "id": "ig009",
        "platform": "instagram",
        "nickname": "@babyworld_zoe",
        "real_name": "Zoe Campbell",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=zoe",
        "followers": "167k",
        "followers_num": 167000,
        "avg_likes": "6.8k",
        "avg_comments": 312,
        "avg_views": "92k",
        "engagement_rate": "4.1%",
        "price_usd": 820,
        "price_display": "$820",
        "tags": ["母婴好物", "育儿分享", "宝宝辅食"],
        "region": "澳大利亚-墨尔本",
        "country": "AU",
        "bio": "Mama of 2 boys 👶 | Evidence-based parenting | Baby essentials",
        "past_brands": ["Ergobaby", "Huggies", "Avent"],
        "fake_risk": 8,
        "niche": "parenting",
        "language": "English",
        "email": "zoe.baby@gmail.com"
    },
    {
        "id": "ig010",
        "platform": "instagram",
        "nickname": "@veganlife_luna",
        "real_name": "Luna Park",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=luna",
        "followers": "234k",
        "followers_num": 234000,
        "avg_likes": "9.6k",
        "avg_comments": 425,
        "avg_views": "130k",
        "engagement_rate": "4.1%",
        "price_usd": 1100,
        "price_display": "$1,100",
        "tags": ["纯素食", "健康饮食", "环保生活"],
        "region": "美国-波特兰",
        "country": "US",
        "bio": "Plant-based chef 🥑 | Vegan recipes that actually taste good",
        "past_brands": ["Beyond Meat", "Oatly", "Whole Foods"],
        "fake_risk": 9,
        "niche": "food",
        "language": "English",
        "email": "luna.vegan@gmail.com"
    }
]

XIAOHONGSHU_INFLUENCERS = [
    {
        "id": "xhs001",
        "platform": "xiaohongshu",
        "nickname": "@海外留学妹子Lily",
        "real_name": "王莉莉",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=lily",
        "followers": "56k",
        "followers_num": 56000,
        "avg_likes": "2.8k",
        "avg_comments": 185,
        "avg_views": "38k",
        "engagement_rate": "5.0%",
        "price_usd": None,
        "price_display": "¥3,000",
        "price_rmb": 3000,
        "tags": ["留学生活", "英美好物", "开箱分享"],
        "region": "英国-伦敦",
        "country": "UK",
        "bio": "在伦敦读研 | 分享英国生活好物 | 留学干货 ✨",
        "past_brands": ["完美日记", "花西子", "Shein"],
        "fake_risk": 8,
        "niche": "lifestyle",
        "language": "Chinese",
        "email": "lily.uk@163.com"
    },
    {
        "id": "xhs002",
        "platform": "xiaohongshu",
        "nickname": "@美国好物测评君",
        "real_name": "张伟",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=zhangwei",
        "followers": "128k",
        "followers_num": 128000,
        "avg_likes": "5.6k",
        "avg_comments": 380,
        "avg_views": "82k",
        "engagement_rate": "4.4%",
        "price_usd": None,
        "price_display": "¥6,000",
        "price_rmb": 6000,
        "tags": ["美国购物", "好物测评", "省钱攻略"],
        "region": "美国-旧金山",
        "country": "US",
        "bio": "定居美国6年 | 帮国内朋友海淘省钱 | 每周更新好物清单",
        "past_brands": ["小米", "UGREEN绿联", "Anker"],
        "fake_risk": 12,
        "niche": "shopping",
        "language": "Chinese",
        "email": "zhangwei.us@gmail.com"
    },
    {
        "id": "xhs003",
        "platform": "xiaohongshu",
        "nickname": "@新加坡美食探店",
        "real_name": "陈晓燕",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=yanyan",
        "followers": "89k",
        "followers_num": 89000,
        "avg_likes": "4.1k",
        "avg_comments": 265,
        "avg_views": "55k",
        "engagement_rate": "4.6%",
        "price_usd": None,
        "price_display": "¥4,500",
        "price_rmb": 4500,
        "tags": ["新加坡美食", "东南亚生活", "探店打卡"],
        "region": "新加坡",
        "country": "SG",
        "bio": "新加坡打工人 | 吃遍狮城 | 东南亚好玩好吃的都在这里",
        "past_brands": ["海底捞", "元気森林", "蒙牛"],
        "fake_risk": 6,
        "niche": "food",
        "language": "Chinese",
        "email": "yanyan.sg@gmail.com"
    },
    {
        "id": "xhs004",
        "platform": "xiaohongshu",
        "nickname": "@日系美妆控Momo",
        "real_name": "刘梦洁",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=momo",
        "followers": "215k",
        "followers_num": 215000,
        "avg_likes": "9.8k",
        "avg_comments": 612,
        "avg_views": "145k",
        "engagement_rate": "4.6%",
        "price_usd": None,
        "price_display": "¥10,000",
        "price_rmb": 10000,
        "tags": ["日本美妆", "日系风格", "好物推荐"],
        "region": "日本-东京",
        "country": "JP",
        "bio": "旅居东京 | 日本美妆第一手情报 | 每月必买清单 💄",
        "past_brands": ["资生堂", "SK-II", "CPB"],
        "fake_risk": 9,
        "niche": "beauty",
        "language": "Chinese",
        "email": "momo.japan@163.com"
    },
    {
        "id": "xhs005",
        "platform": "xiaohongshu",
        "nickname": "@加拿大健身日记",
        "real_name": "李国强",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=guoqiang",
        "followers": "67k",
        "followers_num": 67000,
        "avg_likes": "3.2k",
        "avg_comments": 198,
        "avg_views": "44k",
        "engagement_rate": "4.8%",
        "price_usd": None,
        "price_display": "¥3,500",
        "price_rmb": 3500,
        "tags": ["健身", "加拿大生活", "运动装备"],
        "region": "加拿大-温哥华",
        "country": "CA",
        "bio": "在加拿大健身4年 | 教你用英文网站买到最便宜的运动装备",
        "past_brands": ["Gymshark", "Lululemon", "Optimum Nutrition"],
        "fake_risk": 14,
        "niche": "fitness",
        "language": "Chinese",
        "email": "guoqiang.canada@gmail.com"
    },
    {
        "id": "xhs006",
        "platform": "xiaohongshu",
        "nickname": "@澳洲妈妈圈",
        "real_name": "吴小慧",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=xiaohui",
        "followers": "142k",
        "followers_num": 142000,
        "avg_likes": "6.5k",
        "avg_comments": 420,
        "avg_views": "96k",
        "engagement_rate": "4.6%",
        "price_usd": None,
        "price_display": "¥7,000",
        "price_rmb": 7000,
        "tags": ["澳洲母婴", "海淘好物", "宝宝辅食"],
        "region": "澳大利亚-悉尼",
        "country": "AU",
        "bio": "澳洲两娃妈 | 分享澳洲好物直寄回国 | 母婴产品测评",
        "past_brands": ["Bellamy's", "NUK", "Blackmores"],
        "fake_risk": 5,
        "niche": "parenting",
        "language": "Chinese",
        "email": "xiaohui.au@gmail.com"
    },
    {
        "id": "xhs007",
        "platform": "xiaohongshu",
        "nickname": "@欧洲时尚周记",
        "real_name": "赵雅文",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=yawen",
        "followers": "98k",
        "followers_num": 98000,
        "avg_likes": "4.5k",
        "avg_comments": 285,
        "avg_views": "64k",
        "engagement_rate": "4.6%",
        "price_usd": None,
        "price_display": "¥5,000",
        "price_rmb": 5000,
        "tags": ["欧洲时尚", "轻奢品牌", "穿搭灵感"],
        "region": "法国-巴黎",
        "country": "FR",
        "bio": "在巴黎工作 | 时尚行业5年 | 分享欧洲最新流行趋势 🇫🇷",
        "past_brands": ["ZARA", "Mango", "Sandro"],
        "fake_risk": 11,
        "niche": "fashion",
        "language": "Chinese",
        "email": "yawen.paris@gmail.com"
    },
    {
        "id": "xhs008",
        "platform": "xiaohongshu",
        "nickname": "@美国留学必看",
        "real_name": "孙思远",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=siyuan",
        "followers": "185k",
        "followers_num": 185000,
        "avg_likes": "8.2k",
        "avg_comments": 510,
        "avg_views": "118k",
        "engagement_rate": "4.4%",
        "price_usd": None,
        "price_display": "¥9,000",
        "price_rmb": 9000,
        "tags": ["美国留学", "学习工具", "数码装备"],
        "region": "美国-波士顿",
        "country": "US",
        "bio": "MIT在读 | 留学生必备好物 | 平价高效学习工具测评",
        "past_brands": ["小米", "DJI大疆", "华为"],
        "fake_risk": 7,
        "niche": "education",
        "language": "Chinese",
        "email": "siyuan.mit@gmail.com"
    },
    {
        "id": "xhs009",
        "platform": "xiaohongshu",
        "nickname": "@东南亚探险家",
        "real_name": "林晓晓",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=xiaoxiao",
        "followers": "76k",
        "followers_num": 76000,
        "avg_likes": "3.6k",
        "avg_comments": 228,
        "avg_views": "50k",
        "engagement_rate": "4.7%",
        "price_usd": None,
        "price_display": "¥3,800",
        "price_rmb": 3800,
        "tags": ["东南亚旅行", "小众玩法", "旅行装备"],
        "region": "泰国-清迈",
        "country": "TH",
        "bio": "数字游民 | 东南亚慢游ing | 旅行装备深度测评 🌴",
        "past_brands": ["迪卡侬", "Go Pro", "Osprey"],
        "fake_risk": 13,
        "niche": "travel",
        "language": "Chinese",
        "email": "xiaoxiao.nomad@gmail.com"
    },
    {
        "id": "xhs010",
        "platform": "xiaohongshu",
        "nickname": "@德国工程师日记",
        "real_name": "周建军",
        "avatar": "https://api.dicebear.com/7.x/personas/svg?seed=jianjun",
        "followers": "112k",
        "followers_num": 112000,
        "avg_likes": "5.1k",
        "avg_comments": 328,
        "avg_views": "74k",
        "engagement_rate": "4.6%",
        "price_usd": None,
        "price_display": "¥5,800",
        "price_rmb": 5800,
        "tags": ["德国工具", "高品质好物", "工程师视角"],
        "region": "德国-慕尼黑",
        "country": "DE",
        "bio": "在德国做工程师 | 严选德国制造好物 | 高性价比数码推荐 🔧",
        "past_brands": ["西门子", "Bosch", "OSRAM欧司朗"],
        "fake_risk": 4,
        "niche": "tech",
        "language": "Chinese",
        "email": "jianjun.de@gmail.com"
    }
]

ALL_INFLUENCERS = TIKTOK_INFLUENCERS + INSTAGRAM_INFLUENCERS + XIAOHONGSHU_INFLUENCERS

# 关键词->领域映射，用于AI匹配
NICHE_KEYWORDS = {
    "beauty": ["美妆", "护肤", "彩妆", "口红", "粉底", "眼影", "beauty", "makeup", "skincare", "cosmetic", "lipstick"],
    "fitness": ["健身", "运动", "瑜伽", "减脂", "增肌", "fitness", "workout", "gym", "yoga", "sport"],
    "tech": ["数码", "科技", "手机", "电脑", "耳机", "充电", "tech", "gadget", "phone", "laptop", "electronics"],
    "food": ["美食", "食品", "零食", "饮料", "food", "snack", "drink", "beverage", "recipe", "cooking"],
    "fashion": ["时尚", "穿搭", "服装", "fashion", "clothing", "style", "apparel", "outfit"],
    "lifestyle": ["生活", "家居", "家装", "lifestyle", "home", "decor", "living"],
    "travel": ["旅行", "旅游", "出行", "travel", "trip", "vacation", "adventure"],
    "parenting": ["母婴", "育儿", "宝宝", "妈妈", "parenting", "baby", "kids", "mom", "toddler"],
    "pets": ["宠物", "猫", "狗", "pets", "cat", "dog", "animal"],
    "shopping": ["购物", "好物", "省钱", "shopping", "deals", "bargain"]
}

# 目标市场->国家映射
MARKET_COUNTRY_MAP = {
    "美国": ["US"],
    "英国": ["UK"],
    "欧洲": ["FR", "SE", "NL", "DE", "ES"],
    "东南亚": ["SG", "TH", "MY", "ID"],
    "澳大利亚": ["AU"],
    "日本": ["JP"],
    "韩国": ["KR"],
    "中东": ["AE"],
    "全球": ["US", "UK", "FR", "SE", "NL", "DE", "ES", "SG", "TH", "AU", "JP", "KR", "AE", "CA"],
    "北美": ["US", "CA"],
    "亚太": ["JP", "KR", "SG", "TH", "AU"]
}
